# Generated by Django 2.1.7 on 2020-02-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200116_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
