image: python:3
include:
  - template: Code-Quality.gitlab-ci.yml
code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - pip install -r requirements.txt
  - python manage.py test projects/tests user/tests

staging:
  type: deploy
  image: ruby
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=agreelance-group12 --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
