# Generated by Django 2.1.7 on 2020-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ManyToManyField(related_name='user_reviewer', to='user.Profile'),
        ),
    ]
