# Generated by Django 2.1.7 on 2020-03-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
